### PR TITLE
Adapter support

### PR DESCRIPTION
**Pull request by toadkicker**
Hello,

I wanted to thank you first for building this great library. I've been hacking on it this week to make it much more flexible and support many kinds of graphql implementations. In order to achieve that, I started introducing an adapter pattern. This means developers can introduce their own query building tool provided they implement the appropriate interfaces. Overall my goal is to introduce this library as a dependency in `vuex-orm`'s `plugin-graphql` ecosystem while keeping this library independent. Looking forward to collaborating on it and making this the defacto choice for building graphql queries.

### CODE REVIEW

**Comment by toadkicker** [comment]
* note that I *did not* change index.ts to introduce the other implementations into the library here. This PR is up to start the conversation around the concept and talk about finalizing details.

**Comment by toadkicker** [comment]
so all we would do is implement override methods by extending from the interface
for example, we can create a AppSync adapter and modify the AST’s input when future updates happen. We can just version the adapter and ship a DefaultAppSyncAdapter too.

**Comment by toadkicker** [comment]
Alright all done for now, please review =)

**Comment by atulmy** [comment]
@toadkicker great effort! Will look into it ASAP.

**Comment by atulmy** [comment]
@toadkicker if you think it's good to go, should we merge this to `master` and make an npm release?

**Comment by toadkicker** [comment]
Yeah since this is a big change we probably want to do an RC build and test it

**Comment by atulmy** [comment]
Just to confirm, this update won't change the existing API correct?

**Comment by toadkicker** [comment]
Correct, and I did not change the tests other than adding a test for the adapter argument.

**Comment by atulmy** [comment]
@toadkicker can you provide different possible adapter examples for `query` and `mutation` in Readme?

**Comment by toadkicker** [comment]
I did link to the default adapter, and provided a DefaultAppSyncAdapter for use with AWS AppSync.

**Comment by atulmy** [comment]
@toadkicker hey, if you could resolve the conflicts, I'll go ahead and create a pre release.

**Comment by toadkicker** [comment]
https://tenor.com/Oehp.gif

**Pull request merged**
