### PR TITLE
Generate typings (#1)

### PR DESCRIPTION
**Pull request by DanielHreben**
Turn on typings generation.
I hope this should be enough to use this lib in typescript project, not tested it tbh. https://www.tsmean.com/articles/how-to-write-a-typescript-library/

### CODE REVIEW

**Comment by DanielHreben** [comment]
Thanks for quick merge! Any problems with releasing new version?

**Comment by atulmy** [comment]
Thanks for the contribution. Waiting on issue #8 to get resolved.

**Comment by DanielHreben** [comment]
Hmmm... It does not look like a blocked for release, am I missing something?

**Comment by atulmy** [comment]
Done.

**Comment by DanielHreben** [comment]
Sorry, there is still no `index.d.ts` file, maybe you forgot to run `npm run build` before publish?

**Comment by atulmy** [comment]
I'm not very well versed with TypeScript. Probably @bebraw can help us out?

**Comment by bebraw** [comment]
@atulmy I think it's **package.json** definition. It feels like it's not picking up enough files to publish (excluding `d.ts` by default)? Maybe it needs `"files": ['build/**/*s']` or so.

**Comment by atulmy** [comment]
@bebraw thanks it works.

**Pull request merged**
