### PR TITLE
Generalize API

### LINKED ISSUE #4: Single query, multiple operations
I have a case roughly like this:

```graphql
query SpeakerTweetTemplateQuery($conferenceId: ID!, $contactName: String!) {
  contact(contactName: $contactName, conferenceId: $conferenceId) {
    name
  }
  conference(id: $conferenceId) {
    name
  }
}
```

The point is that I would like to execute multiple operations within a single query. As far as I can see, the current API isn't flexible enough for this purpose.

I can work around this by performing multiple separate requests. Any better ideas? Should I try to PR a generalization like this?

### PR DESCRIPTION
**Pull request by bebraw**
I encoded operation type to the method name (i.e. `query`/`mutation`) and generalized the implementation to support `queries` and `mutations`. I added these methods to avoid ambiguity in typing.

If you prefer `query([<options>])` kind of approach, that's feasible too. I suppose we would drop the two new methods then and fold them into this scheme.

Let me know what you think. Internally it's flexible so it's not a big deal to change the external API.

Closes #4.

### CODE REVIEW

**Comment by atulmy** [comment]
I think it's better to keep only two functions (query, mutation, ~queries~, ~mutations~) exported along with default export to keep the API brief and handle `object` or `[object]` internally. For example, _all the possible cases_ of API would look like:

Named exports:
```
import { query, mutation } from 'gql-query-builder'

query(options: object)
query([options]: object)

mutation(options: object)
mutation([options]: object)
```

Default export:
```
import queryBuilder from 'gql-query-builder'

queryBuilder.query(options: object) 
queryBuilder.query([options]: object)

queryBuilder.mutation(options: object) 
queryBuilder.mutation([options]: object)
```

What do you think?

**Comment by bebraw** [comment]
Yeah, I can fold it to that format. 👍

**Comment by bebraw** [comment]
I did the change.

**Comment by bebraw** [comment]
For `import queryBuilder from 'gql-query-builder'`, you still need `import * as queryBuilder from 'gql-query-builder'` due to the way I export. But maybe that's not too bad.

**Comment by atulmy** [comment]
I think we can still do `import queryBuilder from 'gql-query-builder'` with the current implementation. Source: https://stackoverflow.com/a/38174623/721679

I think Readme also needs a rework for respective changes in API.

**Comment by bebraw** [comment]
> I think we can still do import queryBuilder from 'gql-query-builder' with the current implementation. Source: https://stackoverflow.com/a/38174623/721679

The problem here is that the package is on ES6 module syntax now. If I do `export default { query, mutation }` kind of thing, we get `import builder from 'pkg'` but then CommonJS will be `const { query, mutation } = require('pkg').default` due to the way the compilation works.

If we do what we do now, then CommonJS will be neat. The only cost is that if you want to import all, then you need the `*` syntax.

It's a tradeoff most likely.

> I think Readme also needs a rework for respective changes in API.

I added a brief mention to the intro but we could add full examples as well.

**Comment by atulmy** [comment]
Ah. Then let's keep it as it is:
`import { query, mutation } as queryBuilder from 'gql-query-builder` and
`import * as queryBuilder from 'gql-query-builder`

**Comment by atulmy** [comment]
Also, I think we are missing `index.js` (build) file currently in the repo?

**Comment by bebraw** [comment]
@atulmy The build isn't versioned on purpose. It gets generated on publish and pushed to npm. Thanks for pointing this out, though. There was a bit in the build process I could remove.

If you want, I can also include the build in git instead.

**Comment by atulmy** [comment]
Would be easier if we can generated build manually. Also, the test cases should run against the build file.

**Comment by bebraw** [comment]
> Would be easier if we can generated build manually. Also, the test cases should run against the build file.

There's `npm run build` if you want to inspect the outcome.

What would be the reasoning for testing against the build? That would test the TS compiler itself as far as I can see.

**Comment by atulmy** [comment]
> What would be the reasoning for testing against the build?

To make sure TS compiler spits out error free build. But it's just me not knowing much about TS. 

We can go ahead with the current setup if you think that should work just fine. Let me know.

**Comment by bebraw** [comment]
@atulmy Yeah, I would go with the current and cut a beta release. I can test fairly soon (use case waiting 👍 ).

**Comment by bebraw** [comment]
That said, if we would set up a CI, we could really start testing this (build Matrix against different versions of Node and so on) but that might be too much for a small project.

**Comment by atulmy** [comment]
> that might be too much for a small project
Yes, probably we do not need some server consuming energy for such small project.

Merging.

**Comment by bebraw** [comment]
For future reference, https://docs.travis-ci.com/user/build-matrix/ .

About release, https://docs.npmjs.com/adding-dist-tags-to-packages .

**Pull request merged**
